image: mcr.microsoft.com/dotnet/sdk:5.0

options:
  docker: true
 
pipelines:
  default:
    - step:
        #runs-on: self.hosted - Am I the idiot or smth is wrong with Bitbucket CI
        name: Build, test and deploy
        deployment: staging
        script:
          - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER} 
          
          - dotnet restore
          - dotnet build --no-restore --configuration Release
          - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
          
          - docker build -t silverscreen-api -f Dockerfile .
          - docker image tag silverscreen-api:latest docker-registry.bobost2.net/silverscreen/silverscreen-api:latest
          - docker login docker-registry.bobost2.net --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - docker image push docker-registry.bobost2.net/silverscreen/silverscreen-api:latest