image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
    - step:
        runs-on: self.hosted
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
          - dotnet restore
          - dotnet build --no-restore --configuration Release
          - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
    - step:
        name: Deploy to production
        deployment: production
        runs-on: self.hosted
        trigger: manual 
        script:
          - echo "Test manual deploy"