image: mcr.microsoft.com/dotnet/sdk:5.0

pipelines:
  default:
    - step:
        runs-on: self.hosted
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
          - dotnet restore
          - dotnet build --no-restore --configuration Release
          - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
    - step:
        name: Deploy to staging enviroment
        deployment: staging
        runs-on: self.hosted
        services:
          - docker
        trigger: manual 
        script:
          - docker build -t silverscreen-api .
          - docker image tag silverscreen-api:latest https://docker-registry.bobost2.net/silverscreen/silverscreen-api:latest
          - docker login --username=${regUsr} --password=${regPass}
          - docker image push https://docker-registry.bobost2.net/silverscreen/silverscreen-api:latest